AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Outputs the time
Resources:
  MyBetaStack: 
    Type: AWS::Serverless::Api
    Properties:
      StageName: Qa
  TimeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: ./
      Events:
        MyBetaStack:
          Type: Api
          Properties:
            Path: /TimeResource
            Method: GET
            
